### ISSUE TITLE
doesnt work possibly bc it has to go east

### ISSUE THREAD

**Issue by swatwood** [EdwinWu1423/diligent-computing#6]
java UserOfMazeSolver  mazes/intersection_treasureNorth.txt 1 2 43
-----
| 0 |
|**e|
| * |
-----

Exception in thread "main" java.lang.NullPointerException
	at Maze$Vector.access$400(Maze.java:195)
	at Maze.dropA(Maze.java:173)
	at MazeSolver.solve(MazeSolver.java:29)
	at UserOfMazeSolver.baseTest(UserOfMazeSolver.java:27)
	at UserOfMazeSolver.main(UserOfMazeSolver.java:22)

**Comment by tinawong15** [comment]
See #5 . This should be functioning by using the branch `v0`.
